/**
 * On-Demand Cross-Domain Digest (spec 2-4) — federates the three provenance
 * surfaces stories 2.1-2.3 already built (task `content.provenance`,
 * `self-mod-log.md`, document `FillHistoryEntry.provenance`) into one
 * read-only summary, pulled on demand via `ncl groups provenance-digest`.
 * No new storage, no new provenance shape — this reads the three existing
 * ones as-is and never writes anything.
 *
 * Each section is present even when it has nothing to show — never silently
 * omitted, never an error (see the spec's Boundaries & I/O Matrix).
 */
import fs from 'fs';
import path from 'path';

import type Database from 'better-sqlite3';

import { GROUPS_DIR } from '../config.js';
import { resolveGroupTimezone } from '../container-config.js';
import { getAgentGroup } from '../db/agent-groups.js';
import { getContainerConfig } from '../db/container-configs.js';
import { findTaskSessions } from '../db/sessions.js';
import { log } from '../log.js';
import { cleanReason, parseProvenance } from './provenance.js';
import { parseSelfModLogLine, readSelfModLog } from './self-mod/self-mod-log.js';
import { inboundDbPath, withInboundDb } from '../session-manager.js';
import { formatLocalTime } from '../timezone.js';

// Recency caps — same reasoning as the underlying stores' own caps
// (self-mod-log.md / FillHistoryEntry are each capped at 20): a digest
// answering "what have you automated *recently*" doesn't need a user's
// entire lifetime history in one call.
// review round 1: tasks had no cap at all — unlike the other two sections,
// live task series aren't bounded by any underlying store's own cap, so
// this digest must impose one itself.
const TASK_DIGEST_LIMIT = 10;
const SELF_MOD_DIGEST_LIMIT = 10;
const DOCUMENT_DIGEST_LIMIT = 10;

export interface TaskDigestItem {
  series_id: string;
  session_id: string;
  status: string;
  prompt: string;
  triggered_by: 'user' | 'agent' | null;
  requester_user_id: string | null;
  reason: string | null;
  provenance_at: string | null;
  /**
   * epic retro: this was named `created_at`, which is misleading for a
   * recurring series — it's this specific live *row's* own timestamp (the
   * latest fire for one already past its first), not when the series was
   * originally set up. `provenance_at` is the one that actually answers
   * "when was this created" (fixed at series creation, per AD-8, never
   * regenerated by a later fire) — this field just says when the row you're
   * looking at was written.
   */
  row_timestamp: string;
  row_timestamp_local: string;
}

export interface DocumentDigestItem {
  target: string;
  /** review round 1: a pre-refresh snapshot carries provenance too, but isn't a real fill — label it, don't let it read as one. */
  kind: 'fill' | 'pre-refresh-snapshot';
  triggered_by: 'agent';
  requester_user_id: string | null;
  reason: string | null;
  provenance_at: string;
  timestamp: string;
  timestamp_local: string;
}

/**
 * epic retro (cross-story finding, both adversarial + edge-case-hunter
 * lenses independently): self-mod-log.md carries no separate "row write
 * time" vs "provenance time" split the way tasks/documents do (one action
 * = one line = one timestamp, no recurrence), so this item only needs one
 * timestamp pair. `action`/`reason` name what self-mod-log.md itself calls
 * them (see `SelfModLogEntry`) rather than forcing task/document field
 * names (`prompt`, `target`) onto a domain that has neither.
 */
export interface SelfModDigestItem {
  action: string;
  reason: string | null;
  provenance_at: string;
  provenance_at_local: string;
}

export interface ProvenanceDigestSection<T> {
  /** Always present, plain-language — never omitted, never an error. */
  summary: string;
  items: T[];
}

export interface ProvenanceDigest {
  agent_group_id: string;
  tasks: ProvenanceDigestSection<TaskDigestItem>;
  self_mod: ProvenanceDigestSection<SelfModDigestItem>;
  documents: ProvenanceDigestSection<DocumentDigestItem>;
}

// ---------------------------------------------------------------------------
// Tasks — content.provenance on live (pending/paused) task series.
//
// tasks.ts's own selectLiveTasks/isTaskThread are module-private (not
// exported) — exporting them purely for this one new caller would be a
// larger refactor of already-shipped, well-tested code than this story's
// narrow aggregation purpose warrants (see the spec's Design Notes), so the
// query is still re-implemented against the same real schema. `parseProvenance`
// itself, though, moved to a shared `./provenance.js` module (epic retro
// finding: it used to be a byte-identical duplicate of tasks.ts's own copy,
// both in this same host runtime — no reason not to share it).
// ---------------------------------------------------------------------------

interface LiveTaskRow {
  row_id: string;
  series_id: string | null;
  status: string;
  content: string;
  timestamp: string;
}

function parseTaskContent(raw: string): { prompt: string; provenance: ReturnType<typeof parseProvenance> } {
  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    return {
      prompt: typeof parsed.prompt === 'string' ? parsed.prompt : '',
      provenance: parseProvenance(parsed.provenance),
    };
  } catch {
    // LEGACY-COMPAT(v1-tasks): plain-string content from rows that predate
    // the JSON envelope. Removable once no pre-v2 session DBs remain.
    return { prompt: raw, provenance: undefined };
  }
}

// GROUP BY series_id with un-aggregated columns (id/status/content/timestamp)
// alongside MAX(seq) relies on SQLite's "bare column" extension — the
// non-aggregated columns come from the row holding the max, same as
// tasks.ts's own selectLiveTasks (this file's own precedent, module-private
// there) already relies on. Deliberate, not an accidental portability gap.
function selectLiveTaskRows(db: Database.Database): LiveTaskRow[] {
  return db
    .prepare(
      `SELECT id AS row_id, series_id, status, content, timestamp, MAX(seq) AS seq
         FROM messages_in
        WHERE kind = 'task'
          AND status IN ('pending', 'paused')
        GROUP BY series_id
        ORDER BY timestamp ASC`,
    )
    .all() as LiveTaskRow[];
}

function truncate(text: string, max: number): string {
  if (max <= 3) return text.slice(0, Math.max(max, 0));
  return text.length > max ? text.slice(0, max - 3) + '...' : text;
}

function taskDigestItems(agentGroupId: string, timezone: string): TaskDigestItem[] {
  const items: TaskDigestItem[] = [];
  for (const session of findTaskSessions(agentGroupId)) {
    if (!fs.existsSync(inboundDbPath(agentGroupId, session.id))) continue;
    let rows: LiveTaskRow[];
    try {
      rows = withInboundDb(agentGroupId, session.id, selectLiveTaskRows);
    } catch (e) {
      // review round 1: a locked/corrupted/schema-mismatched session DB must
      // not take down the whole digest — same tolerant posture as the
      // self-mod/document readers, which never throw on a bad individual
      // source. Skip this one session, keep going.
      log.warn('provenance-digest: could not read a task session — skipped', {
        agentGroupId,
        sessionId: session.id,
        err: e,
      });
      continue;
    }
    for (const row of rows) {
      const { prompt, provenance } = parseTaskContent(row.content);
      items.push({
        series_id: row.series_id ?? row.row_id,
        session_id: session.id,
        status: row.status,
        prompt: truncate(prompt, 120),
        triggered_by: provenance?.triggeredBy ?? null,
        requester_user_id: provenance?.requesterUserId ?? null,
        reason: provenance?.reason ? truncate(provenance.reason, 120) : null,
        provenance_at: provenance?.at ?? null,
        row_timestamp: row.timestamp,
        row_timestamp_local: formatLocalTime(row.timestamp, timezone),
      });
    }
  }
  // review round 1: each session's own rows were already ordered, but never
  // sorted globally across sessions, and had no recency cap at all — unlike
  // the other two sections. Newest first, then capped, matching documents'
  // own treatment.
  items.sort((a, b) => (a.row_timestamp < b.row_timestamp ? 1 : a.row_timestamp > b.row_timestamp ? -1 : 0));
  return items.slice(0, TASK_DIGEST_LIMIT);
}

// ---------------------------------------------------------------------------
// Documents — FillHistoryEntry.provenance across `.fill-history/*.json`.
//
// Cross-runtime note (same accepted tradeoff as specs 1.1/1.2/2.2's
// `-shared`/`WORKSPACE_EXTRA_DIR` convention): host `src/**` and container
// `container/agent-runner/src/**` are separate packages/runtimes — no
// shared TS import is possible, so this independently re-encodes
// documents.ts's `.fill-history/<slug>.json` shape, reading only the
// fields this digest needs (timestamp, target, provenance), tolerant of
// anything else, mirroring readFillHistory's own tolerant-reader posture.
// Only entries that actually carry a `provenance` object count for this
// digest — an entry (or a whole directory) with none is, from this
// digest's perspective, indistinguishable from "no document fill history."
// ---------------------------------------------------------------------------

function documentFillHistoryDir(agentGroupId: string): string | undefined {
  const ag = getAgentGroup(agentGroupId);
  if (!ag) return undefined;
  return path.join(GROUPS_DIR, ag.folder, 'memory', 'documents', '.fill-history');
}

function readDocumentProvenanceEntries(agentGroupId: string): Array<Omit<DocumentDigestItem, 'timestamp_local'>> {
  const dir = documentFillHistoryDir(agentGroupId);
  if (!dir) return [];

  let files: string[];
  try {
    files = fs.readdirSync(dir).filter((f) => f.endsWith('.json'));
  } catch (e) {
    // review round 1: ENOENT (never filled anything yet) is genuinely
    // "nothing to show" and stays silent — anything else (permissions, a
    // real I/O error) is a real problem an operator should be able to find,
    // same posture as this codebase's mount-rejection precedent.
    if ((e as NodeJS.ErrnoException).code !== 'ENOENT') {
      log.warn('provenance-digest: could not list document fill-history directory', { agentGroupId, dir, err: e });
    }
    return [];
  }

  const entries: Array<Omit<DocumentDigestItem, 'timestamp_local'>> = [];
  for (const file of files) {
    let raw: string;
    try {
      raw = fs.readFileSync(path.join(dir, file), 'utf-8');
    } catch (e) {
      log.warn('provenance-digest: could not read a fill-history file — skipped', { agentGroupId, file, err: e });
      continue;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (e) {
      log.warn('provenance-digest: a fill-history file is not valid JSON — skipped', { agentGroupId, file, err: e });
      continue;
    }
    if (!Array.isArray(parsed)) continue;

    for (const candidateRaw of parsed) {
      if (!candidateRaw || typeof candidateRaw !== 'object') continue;
      const candidate = candidateRaw as Record<string, unknown>;
      if (typeof candidate.timestamp !== 'string' || typeof candidate.target !== 'string') continue;

      const rawProvenance = candidate.provenance;
      if (!rawProvenance || typeof rawProvenance !== 'object') continue;
      const p = rawProvenance as Record<string, unknown>;
      if (p.triggeredBy !== 'agent' || typeof p.at !== 'string') {
        // epic retro (cross-story finding): documents.ts's own readFillHistory
        // already fixed "a malformed-but-present provenance object dropped
        // with no trace" (its own review round 1) — this sibling re-parse of
        // the identical shape had silently reintroduced the exact same gap.
        log.warn('provenance-digest: a fill-history entry has a malformed provenance object — skipped', {
          agentGroupId,
          file,
        });
        continue;
      }

      entries.push({
        target: candidate.target,
        // review round 1: a pre-refresh snapshot carries provenance too but
        // isn't a real fill — label it the same way documents.ts's own
        // list_document_versions already does, so it never reads as an
        // actual field-fill with a reason.
        kind: candidate.kind === 'pre-refresh-snapshot' ? 'pre-refresh-snapshot' : 'fill',
        triggered_by: 'agent',
        requester_user_id: typeof p.requesterUserId === 'string' ? p.requesterUserId : null,
        // epic retro: re-clean on read too, via the same shared helper every
        // other provenance writer/reader now uses — not just the raw
        // truncate() this file's own writer applies at write time.
        reason: cleanReason(p.reason) ?? null,
        provenance_at: p.at,
        timestamp: candidate.timestamp,
      });
    }
  }

  // Newest first.
  entries.sort((a, b) => (a.timestamp < b.timestamp ? 1 : a.timestamp > b.timestamp ? -1 : 0));
  return entries;
}

function documentDigestItems(agentGroupId: string, timezone: string): DocumentDigestItem[] {
  return readDocumentProvenanceEntries(agentGroupId)
    .slice(0, DOCUMENT_DIGEST_LIMIT)
    .map((entry) => ({ ...entry, timestamp_local: formatLocalTime(entry.timestamp, timezone) }));
}

// ---------------------------------------------------------------------------
// Federation point
// ---------------------------------------------------------------------------

/**
 * Build the cross-domain provenance digest for one agent group. Throws with
 * the same "No container config for group" precedent as `config get` when
 * `agentGroupId` is bad or missing a container config — every other case
 * (no tasks, no self-mod history, no document history) resolves to an empty
 * section with a plain-language summary, never an error.
 */
export function buildProvenanceDigest(agentGroupId: string): ProvenanceDigest {
  if (!getContainerConfig(agentGroupId)) {
    throw new Error(`No container config for group: ${agentGroupId}`);
  }

  const timezone = resolveGroupTimezone(agentGroupId);

  const taskItems = taskDigestItems(agentGroupId, timezone);
  // epic retro (cross-story finding): readSelfModLog's own contract is
  // "newest last" (matching self-mod-log.md's own append-only file order —
  // a deliberate, separately-tested convention this function keeps for any
  // other future caller), but tasks/documents are both newest-first in this
  // digest. Reverse only here, at the point of federation, so every
  // section's index 0 means the same thing in the ONE object meant to unify
  // them — without changing readSelfModLog's own documented order.
  const selfModLines = [...readSelfModLog(agentGroupId, SELF_MOD_DIGEST_LIMIT)].reverse();
  // epic retro (cross-story finding, adversarial + edge-case-hunter lenses):
  // this section used to carry raw, unparsed lines while tasks/documents
  // both used the shared ProvenanceDigestSection<T> shape — the one place
  // meant to federate all three domains under AD-7's shared shape wasn't
  // actually shaped the same. parseSelfModLogLine is the exact inverse of
  // appendSelfModLog's own write format (see that function's own doc
  // comment) — a line it can't parse means the file was hand-edited or
  // corrupted outside this module's control; skip it and log, same
  // tolerant-reader posture as the document/task sections use for their own
  // malformed input.
  const selfModItems: SelfModDigestItem[] = [];
  for (const line of selfModLines) {
    const parsed = parseSelfModLogLine(line);
    if (!parsed) {
      log.warn('provenance-digest: a self-mod-log.md line could not be parsed — skipped', { agentGroupId });
      continue;
    }
    selfModItems.push({
      action: parsed.action,
      reason: parsed.reason,
      provenance_at: parsed.at,
      provenance_at_local: formatLocalTime(parsed.at, timezone),
    });
  }
  const documentItems = documentDigestItems(agentGroupId, timezone);

  return {
    agent_group_id: agentGroupId,
    // review round 1: "N recent ..." reads as a complete count — none of
    // these sections can actually tell whether more exist beyond their own
    // cap, so the wording says "most recent" (a view, not a total) rather
    // than implying completeness.
    tasks: {
      summary:
        taskItems.length > 0
          ? `${taskItems.length} most recent active task${taskItems.length === 1 ? '' : 's'} (up to ${TASK_DIGEST_LIMIT} shown).`
          : 'No active tasks with recorded provenance.',
      items: taskItems,
    },
    self_mod: {
      summary:
        selfModItems.length > 0
          ? `${selfModItems.length} most recent self-modification entr${selfModItems.length === 1 ? 'y' : 'ies'} (up to ${SELF_MOD_DIGEST_LIMIT} shown).`
          : 'No self-modification history recorded yet.',
      items: selfModItems,
    },
    documents: {
      summary:
        documentItems.length > 0
          ? `${documentItems.length} most recent document change${documentItems.length === 1 ? '' : 's'} with recorded provenance (up to ${DOCUMENT_DIGEST_LIMIT} shown).`
          : 'No document fill history with recorded provenance.',
      items: documentItems,
    },
  };
}
